# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'aeonstagram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aeonstagram

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'

  target 'aeonstagram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aeonstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'aeonstagram-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aeonstagram-tvOS

end
